#pragma once

#define ENABLE_OPENGL_DEBUGING

#define MAX_TEXTURE_SLOTS 16

#define ARRAY_BUFFER_REPEATED_BIND_OPTIMIZATION
#define INDEX_BUFFER_REPEATED_BIND_OPTIMIZATION
#define PROGRAM_REPEATED_BIND_OPTIMIZATION
#define TEXTURE_REPEATED_BIND_OPTIMIZATION

#define DEFINE_SHADER_UNIFORMS_UPON_COMPILE

// PhysX  Definitions
#define PVD_HOST "127.0.0.1"
#define PHYSX_THREAD_SIZE 1

// Redis 

#define REDIS_CONNECTION_PRINTS
